// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

package protocol

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*
// basic
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_SUCCESS          ErrorCode = 0
	ErrorCode_ERROR_CODE_INVALID_ARGUMENT ErrorCode = -1
	ErrorCode_ERROR_CODE_QUEUE_FULL       ErrorCode = -2
)

var ErrorCode_name = map[int32]string{
	0:  "ERROR_CODE_SUCCESS",
	-1: "ERROR_CODE_INVALID_ARGUMENT",
	-2: "ERROR_CODE_QUEUE_FULL",
}

var ErrorCode_value = map[string]int32{
	"ERROR_CODE_SUCCESS":          0,
	"ERROR_CODE_INVALID_ARGUMENT": -1,
	"ERROR_CODE_QUEUE_FULL":       -2,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}

func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0}
}

type Field struct {
	Type                 uint32   `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Term                 string   `protobuf:"bytes,2,opt,name=term,proto3" json:"term,omitempty"`
	ValueStr             string   `protobuf:"bytes,3,opt,name=valueStr,proto3" json:"valueStr,omitempty"`
	ValueInt32           int32    `protobuf:"varint,4,opt,name=valueInt32,proto3" json:"valueInt32,omitempty"`
	Indexable            bool     `protobuf:"varint,5,opt,name=indexable,proto3" json:"indexable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0}
}

func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (m *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(m, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Field) GetTerm() string {
	if m != nil {
		return m.Term
	}
	return ""
}

func (m *Field) GetValueStr() string {
	if m != nil {
		return m.ValueStr
	}
	return ""
}

func (m *Field) GetValueInt32() int32 {
	if m != nil {
		return m.ValueInt32
	}
	return 0
}

func (m *Field) GetIndexable() bool {
	if m != nil {
		return m.Indexable
	}
	return false
}

type Document struct {
	Pk                   uint64   `protobuf:"varint,1,opt,name=pk,proto3" json:"pk,omitempty"`
	Fields               []*Field `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Document) Reset()         { *m = Document{} }
func (m *Document) String() string { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()    {}
func (*Document) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{1}
}

func (m *Document) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Document.Unmarshal(m, b)
}
func (m *Document) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Document.Marshal(b, m, deterministic)
}
func (m *Document) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Document.Merge(m, src)
}
func (m *Document) XXX_Size() int {
	return xxx_messageInfo_Document.Size(m)
}
func (m *Document) XXX_DiscardUnknown() {
	xxx_messageInfo_Document.DiscardUnknown(m)
}

var xxx_messageInfo_Document proto.InternalMessageInfo

func (m *Document) GetPk() uint64 {
	if m != nil {
		return m.Pk
	}
	return 0
}

func (m *Document) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

//*
// request
type RequestDocumentAdd struct {
	Documents            []*Document `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RequestDocumentAdd) Reset()         { *m = RequestDocumentAdd{} }
func (m *RequestDocumentAdd) String() string { return proto.CompactTextString(m) }
func (*RequestDocumentAdd) ProtoMessage()    {}
func (*RequestDocumentAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{2}
}

func (m *RequestDocumentAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestDocumentAdd.Unmarshal(m, b)
}
func (m *RequestDocumentAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestDocumentAdd.Marshal(b, m, deterministic)
}
func (m *RequestDocumentAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestDocumentAdd.Merge(m, src)
}
func (m *RequestDocumentAdd) XXX_Size() int {
	return xxx_messageInfo_RequestDocumentAdd.Size(m)
}
func (m *RequestDocumentAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestDocumentAdd.DiscardUnknown(m)
}

var xxx_messageInfo_RequestDocumentAdd proto.InternalMessageInfo

func (m *RequestDocumentAdd) GetDocuments() []*Document {
	if m != nil {
		return m.Documents
	}
	return nil
}

type RequestDocumentRemove struct {
	Pks                  []uint64 `protobuf:"varint,1,rep,packed,name=pks,proto3" json:"pks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestDocumentRemove) Reset()         { *m = RequestDocumentRemove{} }
func (m *RequestDocumentRemove) String() string { return proto.CompactTextString(m) }
func (*RequestDocumentRemove) ProtoMessage()    {}
func (*RequestDocumentRemove) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{3}
}

func (m *RequestDocumentRemove) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestDocumentRemove.Unmarshal(m, b)
}
func (m *RequestDocumentRemove) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestDocumentRemove.Marshal(b, m, deterministic)
}
func (m *RequestDocumentRemove) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestDocumentRemove.Merge(m, src)
}
func (m *RequestDocumentRemove) XXX_Size() int {
	return xxx_messageInfo_RequestDocumentRemove.Size(m)
}
func (m *RequestDocumentRemove) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestDocumentRemove.DiscardUnknown(m)
}

var xxx_messageInfo_RequestDocumentRemove proto.InternalMessageInfo

func (m *RequestDocumentRemove) GetPks() []uint64 {
	if m != nil {
		return m.Pks
	}
	return nil
}

type RequestLookup struct {
	Terms                []string `protobuf:"bytes,1,rep,name=terms,proto3" json:"terms,omitempty"`
	Limit                uint32   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestLookup) Reset()         { *m = RequestLookup{} }
func (m *RequestLookup) String() string { return proto.CompactTextString(m) }
func (*RequestLookup) ProtoMessage()    {}
func (*RequestLookup) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{4}
}

func (m *RequestLookup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestLookup.Unmarshal(m, b)
}
func (m *RequestLookup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestLookup.Marshal(b, m, deterministic)
}
func (m *RequestLookup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestLookup.Merge(m, src)
}
func (m *RequestLookup) XXX_Size() int {
	return xxx_messageInfo_RequestLookup.Size(m)
}
func (m *RequestLookup) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestLookup.DiscardUnknown(m)
}

var xxx_messageInfo_RequestLookup proto.InternalMessageInfo

func (m *RequestLookup) GetTerms() []string {
	if m != nil {
		return m.Terms
	}
	return nil
}

func (m *RequestLookup) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

//*
// response
type ResponseOperate struct {
	Code                 ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=ErrorCode" json:"code,omitempty"`
	Msg                  string    `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ResponseOperate) Reset()         { *m = ResponseOperate{} }
func (m *ResponseOperate) String() string { return proto.CompactTextString(m) }
func (*ResponseOperate) ProtoMessage()    {}
func (*ResponseOperate) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{5}
}

func (m *ResponseOperate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseOperate.Unmarshal(m, b)
}
func (m *ResponseOperate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseOperate.Marshal(b, m, deterministic)
}
func (m *ResponseOperate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseOperate.Merge(m, src)
}
func (m *ResponseOperate) XXX_Size() int {
	return xxx_messageInfo_ResponseOperate.Size(m)
}
func (m *ResponseOperate) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseOperate.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseOperate proto.InternalMessageInfo

func (m *ResponseOperate) GetCode() ErrorCode {
	if m != nil {
		return m.Code
	}
	return ErrorCode_ERROR_CODE_SUCCESS
}

func (m *ResponseOperate) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type ResponseLookup struct {
	Documents            []*Document `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	Code                 ErrorCode   `protobuf:"varint,2,opt,name=code,proto3,enum=ErrorCode" json:"code,omitempty"`
	Msg                  string      `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Total                uint32      `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ResponseLookup) Reset()         { *m = ResponseLookup{} }
func (m *ResponseLookup) String() string { return proto.CompactTextString(m) }
func (*ResponseLookup) ProtoMessage()    {}
func (*ResponseLookup) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{6}
}

func (m *ResponseLookup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseLookup.Unmarshal(m, b)
}
func (m *ResponseLookup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseLookup.Marshal(b, m, deterministic)
}
func (m *ResponseLookup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseLookup.Merge(m, src)
}
func (m *ResponseLookup) XXX_Size() int {
	return xxx_messageInfo_ResponseLookup.Size(m)
}
func (m *ResponseLookup) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseLookup.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseLookup proto.InternalMessageInfo

func (m *ResponseLookup) GetDocuments() []*Document {
	if m != nil {
		return m.Documents
	}
	return nil
}

func (m *ResponseLookup) GetCode() ErrorCode {
	if m != nil {
		return m.Code
	}
	return ErrorCode_ERROR_CODE_SUCCESS
}

func (m *ResponseLookup) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ResponseLookup) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterEnum("ErrorCode", ErrorCode_name, ErrorCode_value)
	proto.RegisterType((*Field)(nil), "Field")
	proto.RegisterType((*Document)(nil), "Document")
	proto.RegisterType((*RequestDocumentAdd)(nil), "RequestDocumentAdd")
	proto.RegisterType((*RequestDocumentRemove)(nil), "RequestDocumentRemove")
	proto.RegisterType((*RequestLookup)(nil), "RequestLookup")
	proto.RegisterType((*ResponseOperate)(nil), "ResponseOperate")
	proto.RegisterType((*ResponseLookup)(nil), "ResponseLookup")
}

func init() { proto.RegisterFile("protocol.proto", fileDescriptor_2bc2336598a3f7e0) }

var fileDescriptor_2bc2336598a3f7e0 = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x3d, 0x8f, 0xd3, 0x40,
	0x10, 0x65, 0x1d, 0x27, 0x8a, 0x07, 0x25, 0x44, 0x23, 0x0e, 0x59, 0x80, 0x22, 0xcb, 0x0d, 0x86,
	0x22, 0x45, 0xae, 0x03, 0x51, 0x44, 0x8e, 0x0f, 0x45, 0x0a, 0x17, 0x31, 0xc1, 0xb4, 0x51, 0x2e,
	0x1e, 0x50, 0x14, 0x3b, 0xbb, 0x67, 0x6f, 0x4e, 0x50, 0x52, 0xf2, 0xa7, 0x01, 0x79, 0xfd, 0x71,
	0x11, 0x05, 0x3a, 0x57, 0xef, 0x3d, 0xbf, 0xd9, 0x79, 0x3b, 0xb3, 0x30, 0x54, 0xb9, 0xd4, 0x72,
	0x27, 0xd3, 0x89, 0x01, 0xfe, 0x2f, 0x01, 0xdd, 0xab, 0x3d, 0xa7, 0x09, 0x22, 0xd8, 0xfa, 0x87,
	0x62, 0x57, 0x78, 0x22, 0x18, 0x90, 0xc1, 0x46, 0xe3, 0x3c, 0x73, 0x2d, 0x4f, 0x04, 0x0e, 0x19,
	0x8c, 0xcf, 0xa1, 0x7f, 0xb7, 0x4d, 0x4f, 0xbc, 0xd6, 0xb9, 0xdb, 0x31, 0x7a, 0xcb, 0x71, 0x0c,
	0x60, 0xf0, 0xe2, 0xa8, 0x2f, 0xa7, 0xae, 0xed, 0x89, 0xa0, 0x4b, 0x67, 0x0a, 0xbe, 0x04, 0x67,
	0x7f, 0x4c, 0xf8, 0xfb, 0xf6, 0x26, 0x65, 0xb7, 0xeb, 0x89, 0xa0, 0x4f, 0xf7, 0x82, 0xff, 0x16,
	0xfa, 0x73, 0xb9, 0x3b, 0x65, 0x7c, 0xd4, 0x38, 0x04, 0x4b, 0x1d, 0x4c, 0x16, 0x9b, 0x2c, 0x75,
	0xc0, 0x31, 0xf4, 0xbe, 0x96, 0x31, 0x0b, 0xd7, 0xf2, 0x3a, 0xc1, 0xe3, 0x69, 0x6f, 0x62, 0x52,
	0x53, 0xad, 0xfa, 0xef, 0x01, 0x89, 0x6f, 0x4f, 0x5c, 0xe8, 0xe6, 0x88, 0x59, 0x92, 0xe0, 0x2b,
	0x70, 0x92, 0x9a, 0x16, 0xae, 0x30, 0x85, 0xce, 0xa4, 0x31, 0xd0, 0xfd, 0x3f, 0xff, 0x35, 0x5c,
	0xfc, 0x53, 0x4e, 0x9c, 0xc9, 0x3b, 0xc6, 0x11, 0x74, 0xd4, 0xa1, 0xaa, 0xb5, 0xa9, 0x84, 0xfe,
	0x3b, 0x18, 0xd4, 0xd6, 0xa5, 0x94, 0x87, 0x93, 0xc2, 0xa7, 0xd0, 0x2d, 0x07, 0x53, 0x99, 0x1c,
	0xaa, 0x48, 0xa9, 0xa6, 0xfb, 0x6c, 0xaf, 0xcd, 0xec, 0x06, 0x54, 0x11, 0x3f, 0x84, 0x27, 0xc4,
	0x85, 0x92, 0xc7, 0x82, 0x57, 0x8a, 0xf3, 0xad, 0x66, 0x1c, 0x83, 0xbd, 0x93, 0x49, 0x35, 0xf7,
	0xe1, 0x14, 0x26, 0x51, 0x9e, 0xcb, 0x3c, 0x94, 0x09, 0x93, 0xd1, 0xcb, 0x04, 0x59, 0xf1, 0xad,
	0x5e, 0x41, 0x09, 0xfd, 0x9f, 0x02, 0x86, 0xcd, 0x29, 0x75, 0x86, 0x87, 0x5e, 0xb4, 0xed, 0x66,
	0xfd, 0xbf, 0x5b, 0xa7, 0xed, 0x66, 0xae, 0x27, 0xf5, 0x36, 0x35, 0xeb, 0x1c, 0x50, 0x45, 0xde,
	0xdc, 0x82, 0xd3, 0x96, 0xe2, 0x33, 0xc0, 0x88, 0x68, 0x45, 0x9b, 0x70, 0x35, 0x8f, 0x36, 0xeb,
	0x38, 0x0c, 0xa3, 0xf5, 0x7a, 0xf4, 0x08, 0x03, 0x78, 0x71, 0xa6, 0x2f, 0xae, 0xbf, 0xcc, 0x96,
	0x8b, 0xf9, 0x66, 0x46, 0x1f, 0xe2, 0x8f, 0xd1, 0xf5, 0xe7, 0xd1, 0x9f, 0xe6, 0x13, 0xe8, 0xc3,
	0xc5, 0x99, 0xf3, 0x53, 0x1c, 0xc5, 0xd1, 0xe6, 0x2a, 0x5e, 0x2e, 0x47, 0xbf, 0x5b, 0xcf, 0x4d,
	0xcf, 0xbc, 0xd8, 0xcb, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9b, 0x47, 0x38, 0x61, 0xc3, 0x02,
	0x00, 0x00,
}
